---
- name: Create terraform folder
  file: >
    path="{{playbook_dir}}/../terraform"
    state=directory

- name: Taint the google_compute_instance.storage resource
  shell: >
    terraform taint -state={{playbook_dir}}/../terraform/terraform.tfstate google_compute_instance.storage chdir={{playbook_dir}}/../terraform/
  register: taint_result
  ignore_errors: yes

- name: Register a no_format flag for cloud init
  set_fact: do_not_format=true
  when: taint_result.rc == 0

- name: Register a no_format flag for cloud init
  set_fact: do_not_format=false
  when: taint_result.rc != 0

- name: Generate terraform file
  template: src=gce.tf.jinja2
            dest="{{playbook_dir}}/../terraform/gce.tf"
- name: Generate cloud-config-storage.yaml file
  template: src=cloud-config-storage.yaml.jinja2
            dest="{{playbook_dir}}/../terraform/cloud-config-storage.yaml"
