- name: Create terraform folder
  file: >
    path="{{playbook_dir}}/../terraform"
    state=directory

- name: Generate terraform file
  template: src=gce.tf.jinja2
            dest="{{playbook_dir}}/../terraform/gce.tf"
- name: Generate cloud-config-storage.yaml file
  template: src=cloud-config-storage.yaml.jinja2
            dest="{{playbook_dir}}/../terraform/cloud-config-storage.yaml"
