- name: Create terraform folder
  file: >
    path="{{playbook_dir}}/../terraform"
    state=directory

- name: Generate terraform file
  template: src=gce.tf.jinja2
            dest="{{playbook_dir}}/../terraform/gce.tf"

- name: register tornado cloud config
  set_fact: >
    inventory_host="tornadohost"

- name: Generate cloud-config-tornado.yaml file
  template: src=cloud-config.yaml.jinja2
            dest="{{playbook_dir}}/../terraform/cloud-config-tornado.yaml"

- name: register redis cloud config
  set_fact: >
    inventory_host="redishost"

- name: Generate cloud-config-redis.yaml file
  template: src=cloud-config.yaml.jinja2
            dest="{{playbook_dir}}/../terraform/cloud-config-redis.yaml"
