---
- name: Run terraform {{mode}}
  shell: >
    terraform {{mode}} -input=false {{playbook_dir}}/../terraform/ chdir={{playbook_dir}}/../terraform/
  when: mode in ['apply', 'plan']

- name: Run terraform destroy
  shell: >
    terraform {{mode}} -input=false -force {{playbook_dir}}/../terraform/ chdir={{playbook_dir}}/../terraform/
  when: mode in ['destroy']