- name: Create terraform folder
  file: >
    path="{{playbook_dir}}/../terraform"
    state=directory

- name: Generate terraform file
  template: src=gce.tf.jinja2
            dest="{{playbook_dir}}/../terraform/gce.tf"

- name: register bar cloud config
  set_fact: >
    tornado_type="bar"

- name: Generate cloud-config-bar.yaml file
  template: src=cloud-config.yaml.jinja2
            dest="{{playbook_dir}}/../terraform/cloud-config-bar.yaml"

- name: register bar cloud config
  set_fact: >
    tornado_type="foo"

- name: Generate cloud-config-foo.yaml file
  template: src=cloud-config.yaml.jinja2
            dest="{{playbook_dir}}/../terraform/cloud-config-foo.yaml"
